-- ============================================================
-- 1_dm.sql
-- CREACIÓN DE LA ESTRUCTURA DEL DATAMART (MODELO ESTRELLA)
-- ============================================================

SET search_path TO estrella, transaccional, public;

-- Limpiar si el proceso falló antes
DROP TABLE IF EXISTS HVENTAS CASCADE;
DROP TABLE IF EXISTS HPRODUCCION CASCADE;
DROP TABLE IF EXISTS HCOMPRAS_MATERIAL CASCADE;
DROP TABLE IF EXISTS HGASTOS_MES CASCADE;
DROP VIEW  IF EXISTS vw_g_ventas_muebleria CASCADE;
DROP TABLE IF EXISTS DTIEMPO CASCADE;
DROP TABLE IF EXISTS DPRODUCTO CASCADE;
DROP TABLE IF EXISTS DCLIENTE CASCADE;
DROP TABLE IF EXISTS DMATERIAL CASCADE;
DROP TABLE IF EXISTS DCATEGORIA_GASTO CASCADE;

-- =========================================
-- DIMENSIONES
-- =========================================

CREATE TABLE DTIEMPO (
    IDFECHA     INT          PRIMARY KEY,  -- YYYYMMDD
    FECHA       DATE         NOT NULL,
    DIA         INT          NOT NULL,
    MES         INT          NOT NULL,
    MESNOMBRE   VARCHAR(15)  NOT NULL,
    TRIMESTRE   INT          NOT NULL,
    ANIO        INT          NOT NULL,
    TEMPORADA   VARCHAR(20),
    ES_PICO     BOOLEAN
);

CREATE TABLE DPRODUCTO (
    IDPRODUCTO    SERIAL        PRIMARY KEY,
    CDPRODUCTO    VARCHAR(60)   NOT NULL UNIQUE,  -- Ampliado para nombres largos
    DSPRODUCTO    VARCHAR(60)   NOT NULL,
    CDCATEGORIA   VARCHAR(40),
    PRECIOVENTA   NUMERIC(10,2),
    COSTOMATERIAL NUMERIC(10,2),
    COSTOMANOOBRA NUMERIC(10,2),
    ES_ESTRELLA   BOOLEAN,
    -- FIX: campos para soportar SCD Tipo 2 en el futuro
    FECHA_DESDE   DATE         DEFAULT CURRENT_DATE,
    FECHA_HASTA   DATE         DEFAULT '9999-12-31',
    ES_VIGENTE    BOOLEAN      DEFAULT TRUE
);

CREATE TABLE DCLIENTE (
    IDCLIENTE     SERIAL        PRIMARY KEY,
    CDCLIENTE     VARCHAR(30)   NOT NULL UNIQUE,
    NOMBRE        VARCHAR(100),
    DOCUMENTO     VARCHAR(20),
    TIPOCLIENTE   VARCHAR(20)   NOT NULL,
    CANAL         VARCHAR(30),
    DIRECCION     TEXT,
    TELEFONO      VARCHAR(20),
    EMAIL         VARCHAR(100),
    LIMITE_CREDITO NUMERIC(12,2),
    SALDO_PENDIENTE NUMERIC(12,2),
    ESTADO        VARCHAR(20),
    FRECUENCIA    VARCHAR(20)
);

CREATE TABLE DMATERIAL (
    IDMATERIAL   SERIAL       PRIMARY KEY,
    -- FIX: clave derivada del nombre, no de ROW_NUMBER (evita inestabilidad)
    CDMATERIAL   VARCHAR(80)  NOT NULL UNIQUE,
    DSMATERIAL   VARCHAR(150) NOT NULL,
    TIPO         VARCHAR(30),
    UNIDADMEDIDA VARCHAR(20),
    PROVEEDOR    VARCHAR(80)
);

CREATE TABLE DCATEGORIA_GASTO (
    IDCATEGORIA  SERIAL       PRIMARY KEY,
    CDCATEGORIA  VARCHAR(20)  NOT NULL UNIQUE,
    DSCATEGORIA  VARCHAR(150) NOT NULL,
    TIPO         VARCHAR(30)
);

-- =========================================
-- TABLAS DE HECHOS
-- =========================================

CREATE TABLE HVENTAS (
    IDVENTA        SERIAL        PRIMARY KEY,
    IDFECHA        INT           NOT NULL REFERENCES DTIEMPO(IDFECHA),
    IDPRODUCTO     INT           NOT NULL REFERENCES DPRODUCTO(IDPRODUCTO),
    IDCLIENTE      INT           NOT NULL REFERENCES DCLIENTE(IDCLIENTE),
    CANTIDAD       NUMERIC(10,3) NOT NULL,
    PRECIOUNITVTA  NUMERIC(10,2) NOT NULL,
    IMPORTETOTAL   NUMERIC(12,2) NOT NULL,
    TIPOVENTA      VARCHAR(20)   NOT NULL,
    COSTOMATTOTAL  NUMERIC(12,2) NOT NULL,
    COSTOMOTOTAL   NUMERIC(12,2),
    COSTOALMACEN   NUMERIC(10,2),
    MARGENCONTRIB  NUMERIC(12,2) NOT NULL,
    PCTMARGEN      NUMERIC(6,2),
    DIASENTIENDA   INT,
    ES_OCIOSO      BOOLEAN,
    COSTOCIOSO     NUMERIC(10,2),
    ES_TEMPORADA   BOOLEAN
);

CREATE TABLE HCOMPRAS_MATERIAL (
    IDCOMPRA       SERIAL        PRIMARY KEY,
    IDFECHA        INT           NOT NULL REFERENCES DTIEMPO(IDFECHA),
    IDMATERIAL     INT           NOT NULL REFERENCES DMATERIAL(IDMATERIAL),
    CANTCOMPRADA   NUMERIC(10,3) NOT NULL,
    PRECIOUNIT     NUMERIC(10,4) NOT NULL,
    TOTALCOMPRA    NUMERIC(12,2) NOT NULL,
    COSTOFLETE     NUMERIC(10,2),
    COSTOCOMPTOTAL NUMERIC(12,2) NOT NULL,
    STOCKANTES     NUMERIC(10,3),
    STOCKDESPUES   NUMERIC(10,3),
    ES_EMERG       BOOLEAN,
    ES_TEMPORADA   BOOLEAN,
    CANTRETAZOS    NUMERIC(10,3)
);

CREATE TABLE HPRODUCCION (
    IDPRODUCCION   SERIAL        PRIMARY KEY,
    IDFECHA        INT           NOT NULL REFERENCES DTIEMPO(IDFECHA),
    IDPRODUCTO     INT           NOT NULL REFERENCES DPRODUCTO(IDPRODUCTO),
    CANTPRODUCIDA  NUMERIC(10,3) NOT NULL,
    COSTOMATTOTAL  NUMERIC(12,2) NOT NULL,
    COSTOMOTOTAL   NUMERIC(12,2) NOT NULL,
    COSTOTOTALPROD NUMERIC(12,2) NOT NULL,
    DESTINO        VARCHAR(30)
);

CREATE TABLE HGASTOS_MES (
    IDGASTO       SERIAL        PRIMARY KEY,
    IDFECHA       INT           NOT NULL REFERENCES DTIEMPO(IDFECHA),
    IDCATEGORIA   INT           NOT NULL REFERENCES DCATEGORIA_GASTO(IDCATEGORIA),
    MONTO         NUMERIC(12,2) NOT NULL,
    DETALLE       TEXT,
    ES_FIJO       BOOLEAN
);

-- =========================================
-- ÍNDICES EN CLAVES FORÁNEAS (mejora consultas analíticas)
-- =========================================

CREATE INDEX idx_hventas_fecha      ON HVENTAS(IDFECHA);
CREATE INDEX idx_hventas_producto   ON HVENTAS(IDPRODUCTO);
CREATE INDEX idx_hventas_cliente    ON HVENTAS(IDCLIENTE);

CREATE INDEX idx_hprod_fecha        ON HPRODUCCION(IDFECHA);
CREATE INDEX idx_hprod_producto     ON HPRODUCCION(IDPRODUCTO);

CREATE INDEX idx_hcompras_fecha     ON HCOMPRAS_MATERIAL(IDFECHA);
CREATE INDEX idx_hcompras_material  ON HCOMPRAS_MATERIAL(IDMATERIAL);

CREATE INDEX idx_hgastos_fecha      ON HGASTOS_MES(IDFECHA);
CREATE INDEX idx_hgastos_categoria  ON HGASTOS_MES(IDCATEGORIA);
