services:
  db_muebleria:
    image: postgres:15
    container_name: postgres_bi
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: muebleria_db
    ports:
      - "5433:5432"
    volumes:
      # Datos persistentes: si borras el contenedor, la BD no se pierde
      - ./postgres_data:/var/lib/postgresql/data

      - ./:/scripts
